### ISSUE TITLE
Check Webpack.config.js

### ISSUE THREAD

**Issue by Maclenn77** [Anjacodes/ToDo_List#3]
Hi, @Anjacodes 

As I'm advancing in the webpack configuration, I remembered a line that caught my attention in your code, and I was wondering if that could cause problems.

In lines 11 and 12, you added:

` 10   new HmtlWebpackPlugin({ `
`  11       title: 'Output Management',`
`  12      template: './src/index.html',`
`  13 }),`
 `  14 ],`

In the steps that I'm following, you should remove line 11 and only keep the template part. Eg.

`    new HmtlWebpackPlugin({`
`         template: './src/index.html',**`
 `   }),`
 ` ],`

Also, you named **HmtlWebpackPlugin** to the plugin (with mt instead tm). I don't think that that is causing any problem, as it's consistent in the document, but it could be confusing later.

Greetings!

**Comment by Anjacodes** [comment]
Thank you for your ideas, JP!
